---

env:
  es6: true
  jest: true

plugins:
  - flowtype

extends:
  # https://github.com/airbnb/javascript
  - airbnb
  - plugin:flowtype/recommended
  - prettier
  - plugin:jest/recommended

parser: babel-eslint

settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true

rules:
  curly:
    - 2
    - all
  arrow-parens:
    - 2
    - as-needed
  semi:
    - 2
    - never
  class-methods-use-this: 0
  comma-dangle:
    - 2
    - always-multiline
  no-console:
    - 2
  no-unused-expressions: 0
  no-param-reassign:
    - 2
    - props: false
  no-useless-escape: 0
  func-names: 0
  quotes:
    - 2
    - single
    - allowTemplateLiterals: true
  no-underscore-dangle: 0
  object-curly-newline: 0
  function-paren-newline: 0
  no-unused-vars:
    - 2
    - argsIgnorePattern: "^_"
  no-else-return:
    - 2
    - allowElseIf: true

  # react
  react/prop-types: 0
  react/jsx-filename-extension: 0
  react/jsx-no-bind:
    - 2
    - ignoreRefs: true
  react/jsx-first-prop-new-line:
    - 2
    - never
  react/jsx-indent-props:
    - 2
    - 2
  react/jsx-closing-bracket-location:
    - 1
    - selfClosing: after-props
      nonEmpty: after-props
  react/prefer-stateless-function:
    - 1
    - ignorePureComponents: true
  react/jsx-boolean-value:
    - 2
    - always
  react/no-unused-prop-types: 0
  react/destructuring-assignment: 0
  react/jsx-one-expression-per-line: 0
  flowtype/delimiter-dangle:
    - 2
    - always-multiline
  flowtype/require-return-type:
    - 2
    - always
    - excludeArrowFunctions: true
      annotateUndefined: always
  import/prefer-default-export: 0
  import/named: 0 # doesn't seem to work with Flow
  import/no-extraneous-dependencies: 0
  import/no-cycle: 0 # FIXME: broken with flow https://github.com/benmosher/eslint-plugin-import/issues/1343
  jest/no-large-snapshots: 1
  jest/no-disabled-tests: 0
  global-require: 0

overrides:
  - files:
      - "src/**/*.js"
    excludedFiles:
      - "*integrationTest.js"
      - "*test.js"
      - "**/__tests__/**"
      - "*test.*.js"
    rules:
      flowtype/require-valid-file-annotation:
        - 2
        - always

globals:
  document: true
  window: true
  self: true
