module.exports = {
  verbose: true,
  bail: true,
  testURL: 'http://localhost/',
  moduleNameMapper: {
    // '^rxjs(.*)$': '<rootDir>/node_modules/rxjs/internal$1',
  },
  setupFilesAfterEnv: ['<rootDir>/src/__tests__/setup.js'],
  rootDir: __dirname,
  modulePaths: ['<rootDir>/src'],
  moduleDirectories: ['<rootDir>/node_modules'],
  restoreMocks: true,
  testMatch: ['**/__tests__/**/?(spec|test).js', '**/?(*.)(spec|test).js'],
  moduleFileExtensions: ['js'],
  modulePathIgnorePatterns: ['<rootDir>/dist', '<rootDir>/dev'],
  collectCoverage: true,
  collectCoverageFrom: ['!**/node_modules/**', 'src/**'],
  coverageDirectory: 'coverage',
  coverageReporters: ['html', 'json'],
  transformIgnorePatterns: ['node_modules/(?!(rambdax|rxjs/_esm2015)/)'],
}
