module.exports = {
  verbose: true,
  bail: true,
  testURL: 'http://localhost/',
  moduleNameMapper: {
    '^rxjs$': '<rootDir>/node_modules/rxjs/internal',
    '^rxjs/(.*)$': '<rootDir>/node_modules/rxjs/internal/$1',
    '^adapters/(.*)$': '<rootDir>/src/adapters/$1',
    '^decorators$': '<rootDir>/src/decorators',
    '^decorators/(.*)$': '<rootDir>/src/decorators/$1',
    '^utils/(.*)$': '<rootDir>/src/utils/$1',
    '^observation/(.*)$': '<rootDir>/src/observation/$1',
    '^Model$': '<rootDir>/src/Model',
    '^Collection$': '<rootDir>/src/Collection',
    '^Database$': '<rootDir>/src/Database',
    '^Database/(.*)$': '<rootDir>/src/Database/$1',
    '^Query$': '<rootDir>/src/Query',
    '^QueryDescription$': '<rootDir>/src/QueryDescription',
    '^RawRecord$': '<rootDir>/src/RawRecord',
    '^Relation$': '<rootDir>/src/Relation',
    '^Schema$': '<rootDir>/src/Schema',
    '^__tests__/(.*)$': '<rootDir>/__tests__/$1',
  },
  setupTestFrameworkScriptFile: '<rootDir>/__tests__/setup.js',
  rootDir: __dirname,
  modulePaths: ['<rootDir>/src'],
  moduleDirectories: ['<rootDir>/node_modules'],
  restoreMocks: true,
  testMatch: ['**/__tests__/**/?(spec|test).js', '**/?(*.)(spec|test).js'],
  moduleFileExtensions: ['js'],
  modulePathIgnorePatterns: ['<rootDir>/dist'],
}
