source 'https://github.com/CocoaPods/Specs.git'
workspace 'WatermelonTester.xcworkspace'

target 'WatermelonTester' do
  platform :ios, '11.3'

  target 'WatermelonTesterTests' do
    inherit! :search_paths
    use_frameworks!
  end
end
