#!/bin/bash

set -e

cp README.md ./docs-website/docs/docs/README.md && \
cp CONTRIBUTING.md ./docs-website/docs/docs/CONTRIBUTING.md && \
cp CHANGELOG.md ./docs-website/docs/docs/CHANGELOG.md && \
sed -i  "s/\/docs-website\/docs\/docs//g" ./docs-website/docs/docs/CHANGELOG.md && \
cd ./docs-website && \
yarn deploy