#!/bin/bash

if ! [ -x "$(command -v mdbook)" ]; then
  echo ""
  echo "You will need to install mdbook to run this script, check https://github.com/rust-lang-nursery/mdBook" >&2
  echo ""
  exit 1
fi

cp README.md ./docs/README.md
cp CONTRIBUTING.md ./docs/CONTRIBUTING.md
cp CHANGELOG.md ./docs/CHANGELOG.md

mdbook build ./docs
