import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  logo: {
    width: 300,
    height: 65,
    maxWidth: '100%',
    marginVertical: 20,
    alignSelf: 'center',
    flex: 1,
  },
  title: { fontSize: 26, fontWeight: 'bold', color: 'black' },
  subtitle: {
    fontSize: 16,
    fontWeight: '500',
    paddingVertical: 10,
    color: '#333',
  },
  body: { paddingVertical: 10, color: '#333', lineHeight: 20 },
  container: { flex: 1, paddingHorizontal: 10, marginVertical: 10 },
  header: {
    flex: 1,
    padding: 10,
    textAlign: 'center',
    fontSize: 16,
    fontWeight: '500',
  },
  marginContainer: { marginVertical: 10 },
  buttonContainer: { flex: 1, flexDirection: 'row', justifyContent: 'center' },
  button: Platform.select({ android: { marginHorizontal: 12, marginBottom: 15 } }),
  listItem: {
    backgroundColor: '#f0f0f0',
    height: Platform.select({ android: 56, ios: 44 }),
    borderTopWidth: 1,
    borderBottomWidth: 1,
    marginTop: -1,
    borderColor: '#ddd',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
  },
  listItemTitle: { flex: 1, fontWeight: '500' },
  listItemCounter: { width: 30, textAlign: 'right', opacity: 0.6 },
  post: { textAlign: 'center', padding: 7, opacity: 0.7 },
  topPadding: { paddingTop: 15 },
  comment: {
    backgroundColor: '#f0f0f0',
    padding: 10,
    paddingVertical: 15,
    marginVertical: 5,
    borderRadius: 10,
    borderColor: '#e0e0e0',
    borderWidth: 1,
  },
  postsListHeader: {
    fontSize: 16,
    fontWeight: '500',
    marginTop: 10,
    padding: 10,
  },
});
